#!/usr/bin/env bash

function print_help {
  echo "SYNOPSIS"
  echo "        Usage: mwah <word>"
  echo ""
  echo "DESCRIPTION"
  echo "        mwah is a CLI tool that fetches dictionary definitons from"
  echo "        Merriam Webster and formats them in a nice way"
  echo ""
  echo "        Make sure to place your API key in \$HOME/.local/share/mwah/key"
}

# reads from stdin
function stringify_tokens {
  str=""
  while read line; do
    [[ -z "$line" ]] && break
    str="$str$line"
  done

  str="${str//\{b\}/}"
  str="${str//\{\/b\}/}"
  str="${str//\{bc\}/: }"
  str="${str//\{inf\}/}"
  str="${str//\{\/inf\}/}"
  str="${str//\{it\}/}"
  str="${str//\{\/it\}/}"
  str="${str//\{ldquo\}/\"}"
  str="${str//\{rdquo\}/\"}"
  str="${str//\{sc\}/}"
  str="${str//\{\/sc\}/}"
  str="${str//\{sup\}/}"
  str="${str//\{\/sup\}/}"
  str="${str//\{t\}/  }"
  str="${str//\{d_link|/}"
  str="${str//\{sx|/}"
  str="${str//|[a-zA-Z]*\}/}"
  str="${str//||\}/}"

  echo -e "$str"
}

################################################################################
# main
################################################################################

key="$(cat $HOME/.local/share/mwah/key)"
if [[ -z "$key" ]]; then
  echo "ERROR: \$HOME/.local/share/mwah/key is empty or does not exist"
  exit 1
fi

if [[ -z "$1" ]]; then
  echo "ERROR: expected exactly one argument"
  exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  print_help
  exit 0
fi

word=$1
# json=$(curl https://www.dictionaryapi.com/api/v3/references/collegiate/json/$word?key=$key --silent)
json=$(cat polish)

echo "$json" | jq

echo "$json" | jq '.[0].meta' &> /dev/null
if [[ "$?" != "0" ]]; then
  echo "ERROR: unable to find definiton for $word"
  exit 1
fi

pos_amt=$(echo "$json" | jq length)
echo "pos_amt: $pos_amt"

for (( posi=0; posi<$pos_amt; posi++ )); do
  pos_json=$(echo "$json" | jq ".[$posi].def")
  type_amt=$(echo "$pos_json" | jq length)
  echo "type_amt: $type_amt"

  for (( typei=0; typei<$type_amt; typei++ )); do
    type_json=$(echo "$pos_json" | jq ".[$typei].sseq")
    def_amt=$(echo "$type_json" | jq length)

    for (( defi=0; defi<$def_amt; defi++ )); do
      def_json=$(echo "$type_json" | jq ".[$defi]")
      sub_amt=$(echo "$def_json" | jq length)
      echo "sub_amt: $sub_amt"

      for (( subi=0; subi<$sub_amt; subi++ )); do
        sub_json=$(echo "$def_json" | jq ".[$subi][0]")

        if [[ $sub_amt -gt 1 && $subi -eq 0 ]]; then
          sub_text=$(echo "$sub_json" | jq -cr '.[1].sense.dt[0][1]')
        elif [[ $sub_amt -gt 1 && $subi -gt 0 ]]; then
          sub_text="{t}$(echo "$sub_json" | jq -cr '.[1].dt[0][1]')"
        else
          sub_text=$(echo "$sub_json" | jq -cr '.[1].dt[0][1]')
        fi
        echo "$sub_text" | stringify_tokens
      done
    done
  done
done
