#!/usr/bin/env bash

function print_help {
  echo "SYNOPSIS"
  echo "        Usage: mwah <word>"
  echo ""
  echo "DESCRIPTION"
  echo "        mwah is a CLI tool that fetches dictionary definitons from"
  echo "        Merriam Webster and formats them in a nice way"
  echo ""
  echo "        Make sure to place your API key in \$HOME/.local/share/mwah/key"
}

# reads from stdin
function stringify_tokens {
  str=""
  while read line; do
    [[ -z "$line" ]] && break
    str="$str\n$line"
  done

  str="${str//\{b\}/}"
  str="${str//\{\/b\}/}"
  str="${str//\{bc\}/: }"
  str="${str//\{inf\}/}"
  str="${str//\{\/inf\}/}"
  str="${str//\{it\}/}"
  str="${str//\{\/it\}/}"
  str="${str//\{ldquo\}/\"}"
  str="${str//\{rdquo\}/\"}"
  str="${str//\{sc\}/}"
  str="${str//\{\/sc\}/}"
  str="${str//\{sup\}/}"
  str="${str//\{\/sup\}/}"

  echo -e "$str"
}

################################################################################
# main
################################################################################

key="$(cat $HOME/.local/share/mwah/key)"
if [[ -z "$key" ]]; then
  echo "ERROR: \$HOME/.local/share/mwah/key is empty or does not exist"
  exit 1
fi

if [[ -z "$1" ]]; then
  echo "ERROR: expected exactly one argument"
  exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  print_help
  exit 0
fi

word=$1
json=$(curl https://www.dictionaryapi.com/api/v3/references/collegiate/json/$word?key=$key)

echo "$json" | jq '.[0].meta' &> /dev/null
if [[ "$?" != "0" ]]; then
  echo "ERROR: unable to find definiton for $word"
  exit 1
fi

defs_json=$(echo "$json" | jq '.[0].def[0].sseq')

def_amt=$(echo "$json" | jq length)

for (( defi=0; defi<$def_amt; defi++ )); do
  def_json=$(echo "$defs_json" | jq ".[$defi]")
  sub_amt=$(echo "$def_json" | jq length)

  for (( subi=0; subi<$sub_amt; subi++ )); do
    sub_json=$(echo "$def_json" | jq ".[$subi]")

    if [[ $sub_amt -gt 1 && $subi -eq 0 ]]; then
      sub_text=$(echo "$sub_json" | jq '.[1].sense.dt[0][1]')
    else
      sub_text=$(echo "$sub_json" | jq '.[1].dt[0][1]')
    fi
    echo "$sub_text" | stringify_tokens
  done
done
